insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Afghanistan", "AF", "AFG", "4", "33", "65" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Albania", "AL", "ALB", "8", "41", "20" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Algeria", "DZ", "DZA", "12", "28", "3" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "American Samoa", "AS", "ASM", "16", "-14.3333", "-170" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Andorra", "AD", "AND", "20", "42.5", "1.6" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Angola", "AO", "AGO", "24", "-12.5", "18.5" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Anguilla", "AI", "AIA", "660", "18.25", "-63.1667" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Antarctica", "AQ", "ATA", "10", "-90", "0" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Antigua and Barbuda", "AG", "ATG", "28", "17.05", "-61.8" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Argentina", "AR", "ARG", "32", "-34", "-64" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Armenia", "AM", "ARM", "51", "40", "45" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Aruba", "AW", "ABW", "533", "12.5", "-69.9667" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Australia", "AU", "AUS", "36", "-27", "133" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Austria", "AT", "AUT", "40", "47.3333", "13.3333" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Azerbaijan", "AZ", "AZE", "31", "40.5", "47.5" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Bahamas", "BS", "BHS", "44", "24.25", "-76" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Bahrain", "BH", "BHR", "48", "26", "50.55" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Bangladesh", "BD", "BGD", "50", "24", "90" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Barbados", "BB", "BRB", "52", "13.1667", "-59.5333" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Belarus", "BY", "BLR", "112", "53", "28" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Belgium", "BE", "BEL", "56", "50.8333", "4" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Belize", "BZ", "BLZ", "84", "17.25", "-88.75" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Benin", "BJ", "BEN", "204", "9.5", "2.25" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Bermuda", "BM", "BMU", "60", "32.3333", "-64.75" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Bhutan", "BT", "BTN", "64", "27.5", "90.5" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Bolivia, Plurinational State of", "BO", "BOL", "68", "-17", "-65" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Bolivia", "BO", "BOL", "68", "-17", "-65" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Bosnia and Herzegovina", "BA", "BIH", "70", "44", "18" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Botswana", "BW", "BWA", "72", "-22", "24" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Bouvet Island", "BV", "BVT", "74", "-54.4333", "3.4" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Brazil", "BR", "BRA", "76", "-10", "-55" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "British Indian Ocean Territory", "IO", "IOT", "86", "-6", "71.5" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Brunei Darussalam", "BN", "BRN", "96", "4.5", "114.6667" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Brunei", "BN", "BRN", "96", "4.5", "114.6667" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Bulgaria", "BG", "BGR", "100", "43", "25" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Burkina Faso", "BF", "BFA", "854", "13", "-2" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Burundi", "BI", "BDI", "108", "-3.5", "30" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Cambodia", "KH", "KHM", "116", "13", "105" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Cameroon", "CM", "CMR", "120", "6", "12" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Canada", "CA", "CAN", "124", "60", "-95" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Cape Verde", "CV", "CPV", "132", "16", "-24" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Cayman Islands", "KY", "CYM", "136", "19.5", "-80.5" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Central African Republic", "CF", "CAF", "140", "7", "21" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Chad", "TD", "TCD", "148", "15", "19" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Chile", "CL", "CHL", "152", "-30", "-71" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "China", "CN", "CHN", "156", "35", "105" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Christmas Island", "CX", "CXR", "162", "-10.5", "105.6667" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Cocos (Keeling) Islands", "CC", "CCK", "166", "-12.5", "96.8333" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Colombia", "CO", "COL", "170", "4", "-72" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Comoros", "KM", "COM", "174", "-12.1667", "44.25" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Congo", "CG", "COG", "178", "-1", "15" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Congo, the Democratic Republic of the", "CD", "COD", "180", "0", "25" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Cook Islands", "CK", "COK", "184", "-21.2333", "-159.7667" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Costa Rica", "CR", "CRI", "188", "10", "-84" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Côte d'Ivoire", "CI", "CIV", "384", "8", "-5" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Ivory Coast", "CI", "CIV", "384", "8", "-5" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Croatia", "HR", "HRV", "191", "45.1667", "15.5" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Cuba", "CU", "CUB", "192", "21.5", "-80" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Cyprus", "CY", "CYP", "196", "35", "33" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Czech Republic", "CZ", "CZE", "203", "49.75", "15.5" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Denmark", "DK", "DNK", "208", "56", "10" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Djibouti", "DJ", "DJI", "262", "11.5", "43" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Dominica", "DM", "DMA", "212", "15.4167", "-61.3333" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Dominican Republic", "DO", "DOM", "214", "19", "-70.6667" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Ecuador", "EC", "ECU", "218", "-2", "-77.5" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Egypt", "EG", "EGY", "818", "27", "30" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "El Salvador", "SV", "SLV", "222", "13.8333", "-88.9167" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Equatorial Guinea", "GQ", "GNQ", "226", "2", "10" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Eritrea", "ER", "ERI", "232", "15", "39" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Estonia", "EE", "EST", "233", "59", "26" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Ethiopia", "ET", "ETH", "231", "8", "38" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Falkland Islands (Malvinas)", "FK", "FLK", "238", "-51.75", "-59" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Faroe Islands", "FO", "FRO", "234", "62", "-7" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Fiji", "FJ", "FJI", "242", "-18", "175" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Finland", "FI", "FIN", "246", "64", "26" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "France", "FR", "FRA", "250", "46", "2" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "French Guiana", "GF", "GUF", "254", "4", "-53" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "French Polynesia", "PF", "PYF", "258", "-15", "-140" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "French Southern Territories", "TF", "ATF", "260", "-43", "67" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Gabon", "GA", "GAB", "266", "-1", "11.75" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Gambia", "GM", "GMB", "270", "13.4667", "-16.5667" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Georgia", "GE", "GEO", "268", "42", "43.5" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Germany", "DE", "DEU", "276", "51", "9" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Ghana", "GH", "GHA", "288", "8", "-2" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Gibraltar", "GI", "GIB", "292", "36.1833", "-5.3667" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Greece", "GR", "GRC", "300", "39", "22" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Greenland", "GL", "GRL", "304", "72", "-40" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Grenada", "GD", "GRD", "308", "12.1167", "-61.6667" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Guadeloupe", "GP", "GLP", "312", "16.25", "-61.5833" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Guam", "GU", "GUM", "316", "13.4667", "144.7833" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Guatemala", "GT", "GTM", "320", "15.5", "-90.25" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Guernsey", "GG", "GGY", "831", "49.5", "-2.56" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Guinea", "GN", "GIN", "324", "11", "-10" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Guinea-Bissau", "GW", "GNB", "624", "12", "-15" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Guyana", "GY", "GUY", "328", "5", "-59" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Haiti", "HT", "HTI", "332", "19", "-72.4167" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Heard Island and McDonald Islands", "HM", "HMD", "334", "-53.1", "72.5167" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Holy See (Vatican City State)", "VA", "VAT", "336", "41.9", "12.45" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Honduras", "HN", "HND", "340", "15", "-86.5" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Hong Kong", "HK", "HKG", "344", "22.25", "114.1667" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Hungary", "HU", "HUN", "348", "47", "20" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Iceland", "IS", "ISL", "352", "65", "-18" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "India", "IN", "IND", "356", "20", "77" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Indonesia", "ID", "IDN", "360", "-5", "120" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Iran, Islamic Republic of", "IR", "IRN", "364", "32", "53" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Iraq", "IQ", "IRQ", "368", "33", "44" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Ireland", "IE", "IRL", "372", "53", "-8" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Isle of Man", "IM", "IMN", "833", "54.23", "-4.55" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Israel", "IL", "ISR", "376", "31.5", "34.75" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Italy", "IT", "ITA", "380", "42.8333", "12.8333" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Jamaica", "JM", "JAM", "388", "18.25", "-77.5" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Japan", "JP", "JPN", "392", "36", "138" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Jersey", "JE", "JEY", "832", "49.21", "-2.13" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Jordan", "JO", "JOR", "400", "31", "36" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Kazakhstan", "KZ", "KAZ", "398", "48", "68" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Kenya", "KE", "KEN", "404", "1", "38" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Kiribati", "KI", "KIR", "296", "1.4167", "173" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Korea, Democratic People's Republic of", "KP", "PRK", "408", "40", "127" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Korea, Republic of", "KR", "KOR", "410", "37", "127.5" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "South Korea", "KR", "KOR", "410", "37", "127.5" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Kuwait", "KW", "KWT", "414", "29.3375", "47.6581" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Kyrgyzstan", "KG", "KGZ", "417", "41", "75" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Lao People's Democratic Republic", "LA", "LAO", "418", "18", "105" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Latvia", "LV", "LVA", "428", "57", "25" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Lebanon", "LB", "LBN", "422", "33.8333", "35.8333" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Lesotho", "LS", "LSO", "426", "-29.5", "28.5" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Liberia", "LR", "LBR", "430", "6.5", "-9.5" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Libyan Arab Jamahiriya", "LY", "LBY", "434", "25", "17" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Libya", "LY", "LBY", "434", "25", "17" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Liechtenstein", "LI", "LIE", "438", "47.1667", "9.5333" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Lithuania", "LT", "LTU", "440", "56", "24" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Luxembourg", "LU", "LUX", "442", "49.75", "6.1667" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Macao", "MO", "MAC", "446", "22.1667", "113.55" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Macedonia, the former Yugoslav Republic of", "MK", "MKD", "807", "41.8333", "22" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Madagascar", "MG", "MDG", "450", "-20", "47" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Malawi", "MW", "MWI", "454", "-13.5", "34" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Malaysia", "MY", "MYS", "458", "2.5", "112.5" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Maldives", "MV", "MDV", "462", "3.25", "73" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Mali", "ML", "MLI", "466", "17", "-4" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Malta", "MT", "MLT", "470", "35.8333", "14.5833" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Marshall Islands", "MH", "MHL", "584", "9", "168" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Martinique", "MQ", "MTQ", "474", "14.6667", "-61" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Mauritania", "MR", "MRT", "478", "20", "-12" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Mauritius", "MU", "MUS", "480", "-20.2833", "57.55" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Mayotte", "YT", "MYT", "175", "-12.8333", "45.1667" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Mexico", "MX", "MEX", "484", "23", "-102" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Micronesia, Federated States of", "FM", "FSM", "583", "6.9167", "158.25" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Moldova, Republic of", "MD", "MDA", "498", "47", "29" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Monaco", "MC", "MCO", "492", "43.7333", "7.4" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Mongolia", "MN", "MNG", "496", "46", "105" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Montenegro", "ME", "MNE", "499", "42", "19" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Montserrat", "MS", "MSR", "500", "16.75", "-62.2" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Morocco", "MA", "MAR", "504", "32", "-5" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Mozambique", "MZ", "MOZ", "508", "-18.25", "35" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Myanmar", "MM", "MMR", "104", "22", "98" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Burma", "MM", "MMR", "104", "22", "98" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Namibia", "NA", "NAM", "516", "-22", "17" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Nauru", "NR", "NRU", "520", "-0.5333", "166.9167" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Nepal", "NP", "NPL", "524", "28", "84" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Netherlands", "NL", "NLD", "528", "52.5", "5.75" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Netherlands Antilles", "AN", "ANT", "530", "12.25", "-68.75" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "New Caledonia", "NC", "NCL", "540", "-21.5", "165.5" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "New Zealand", "NZ", "NZL", "554", "-41", "174" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Nicaragua", "NI", "NIC", "558", "13", "-85" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Niger", "NE", "NER", "562", "16", "8" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Nigeria", "NG", "NGA", "566", "10", "8" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Niue", "NU", "NIU", "570", "-19.0333", "-169.8667" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Norfolk Island", "NF", "NFK", "574", "-29.0333", "167.95" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Northern Mariana Islands", "MP", "MNP", "580", "15.2", "145.75" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Norway", "NO", "NOR", "578", "62", "10" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Oman", "OM", "OMN", "512", "21", "57" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Pakistan", "PK", "PAK", "586", "30", "70" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Palau", "PW", "PLW", "585", "7.5", "134.5" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Palestinian Territory, Occupied", "PS", "PSE", "275", "32", "35.25" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Panama", "PA", "PAN", "591", "9", "-80" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Papua New Guinea", "PG", "PNG", "598", "-6", "147" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Paraguay", "PY", "PRY", "600", "-23", "-58" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Peru", "PE", "PER", "604", "-10", "-76" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Philippines", "PH", "PHL", "608", "13", "122" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Pitcairn", "PN", "PCN", "612", "-24.7", "-127.4" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Poland", "PL", "POL", "616", "52", "20" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Portugal", "PT", "PRT", "620", "39.5", "-8" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Puerto Rico", "PR", "PRI", "630", "18.25", "-66.5" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Qatar", "QA", "QAT", "634", "25.5", "51.25" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Réunion", "RE", "REU", "638", "-21.1", "55.6" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Romania", "RO", "ROU", "642", "46", "25" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Russian Federation", "RU", "RUS", "643", "60", "100" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Russia", "RU", "RUS", "643", "60", "100" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Rwanda", "RW", "RWA", "646", "-2", "30" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Saint Helena, Ascension and Tristan da Cunha", "SH", "SHN", "654", "-15.9333", "-5.7" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Saint Kitts and Nevis", "KN", "KNA", "659", "17.3333", "-62.75" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Saint Lucia", "LC", "LCA", "662", "13.8833", "-61.1333" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Saint Pierre and Miquelon", "PM", "SPM", "666", "46.8333", "-56.3333" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Saint Vincent and the Grenadines", "VC", "VCT", "670", "13.25", "-61.2" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Saint Vincent & the Grenadines", "VC", "VCT", "670", "13.25", "-61.2" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "St. Vincent and the Grenadines", "VC", "VCT", "670", "13.25", "-61.2" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Samoa", "WS", "WSM", "882", "-13.5833", "-172.3333" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "San Marino", "SM", "SMR", "674", "43.7667", "12.4167" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Sao Tome and Principe", "ST", "STP", "678", "1", "7" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Saudi Arabia", "SA", "SAU", "682", "25", "45" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Senegal", "SN", "SEN", "686", "14", "-14" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Serbia", "RS", "SRB", "688", "44", "21" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Seychelles", "SC", "SYC", "690", "-4.5833", "55.6667" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Sierra Leone", "SL", "SLE", "694", "8.5", "-11.5" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Singapore", "SG", "SGP", "702", "1.3667", "103.8" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Slovakia", "SK", "SVK", "703", "48.6667", "19.5" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Slovenia", "SI", "SVN", "705", "46", "15" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Solomon Islands", "SB", "SLB", "90", "-8", "159" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Somalia", "SO", "SOM", "706", "10", "49" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "South Africa", "ZA", "ZAF", "710", "-29", "24" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "South Georgia and the South Sandwich Islands", "GS", "SGS", "239", "-54.5", "-37" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "South Sudan", "SS", "SSD", "728", "8", "30" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Spain", "ES", "ESP", "724", "40", "-4" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Sri Lanka", "LK", "LKA", "144", "7", "81" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Sudan", "SD", "SDN", "736", "15", "30" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Suriname", "SR", "SUR", "740", "4", "-56" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Svalbard and Jan Mayen", "SJ", "SJM", "744", "78", "20" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Swaziland", "SZ", "SWZ", "748", "-26.5", "31.5" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Sweden", "SE", "SWE", "752", "62", "15" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Switzerland", "CH", "CHE", "756", "47", "8" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Syrian Arab Republic", "SY", "SYR", "760", "35", "38" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Taiwan, Province of China", "TW", "TWN", "158", "23.5", "121" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Taiwan", "TW", "TWN", "158", "23.5", "121" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Tajikistan", "TJ", "TJK", "762", "39", "71" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Tanzania, United Republic of", "TZ", "TZA", "834", "-6", "35" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Thailand", "TH", "THA", "764", "15", "100" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Timor-Leste", "TL", "TLS", "626", "-8.55", "125.5167" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Togo", "TG", "TGO", "768", "8", "1.1667" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Tokelau", "TK", "TKL", "772", "-9", "-172" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Tonga", "TO", "TON", "776", "-20", "-175" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Trinidad and Tobago", "TT", "TTO", "780", "11", "-61" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Tunisia", "TN", "TUN", "788", "34", "9" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Turkey", "TR", "TUR", "792", "39", "35" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Turkmenistan", "TM", "TKM", "795", "40", "60" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Turks and Caicos Islands", "TC", "TCA", "796", "21.75", "-71.5833" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Tuvalu", "TV", "TUV", "798", "-8", "178" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Uganda", "UG", "UGA", "800", "1", "32" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Ukraine", "UA", "UKR", "804", "49", "32" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "United Arab Emirates", "AE", "ARE", "784", "24", "54" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "United Kingdom", "GB", "GBR", "826", "54", "-2" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "United States", "US", "USA", "840", "38", "-97" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "United States Minor Outlying Islands", "UM", "UMI", "581", "19.2833", "166.6" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Uruguay", "UY", "URY", "858", "-33", "-56" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Uzbekistan", "UZ", "UZB", "860", "41", "64" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Vanuatu", "VU", "VUT", "548", "-16", "167" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Venezuela, Bolivarian Republic of", "VE", "VEN", "862", "8", "-66" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Venezuela", "VE", "VEN", "862", "8", "-66" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Viet Nam", "VN", "VNM", "704", "16", "106" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Vietnam", "VN", "VNM", "704", "16", "106" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Virgin Islands, British", "VG", "VGB", "92", "18.5", "-64.5" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Virgin Islands, U.S.", "VI", "VIR", "850", "18.3333", "-64.8333" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Wallis and Futuna", "WF", "WLF", "876", "-13.3", "-176.2" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Western Sahara", "EH", "ESH", "732", "24.5", "-13" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Yemen", "YE", "YEM", "887", "15", "48" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Zambia", "ZM", "ZMB", "894", "-15", "30" );
insert into COUNTRIES (NAME, A2CODE, A3CODE, NCODE, MLAT, MLONG) values ( "Zimbabwe", "ZW", "ZWE", "716", "-20", "30" );
