const Titles={
    'it': {
        'addOpportunity':'NUOVA OPPORTUNITA\'',
        'customers':'CUSTOMERS',
        'dashboard':'DASHBOARD',
        'opportunities':'OPPORTUNITA\'',
        'setup':'IMPOSTAZIONI',
    },
    'en': {
        'addOpportunity':'NEW OPPORTUNITY',
        'customers':'CUSTOMERS',
        'dashboard':'DASHBOARDS',
        'opportunities':'OPPORTUNITIES',
        'setup':'SET-UP',
    }
};

const MenusItems={
    'it': {
        'amount':'AMMONTARE',
        'assignedto':'ASSEGNATA A',
        'bu':'FUNZIONE     ',
        'cancel':'ANNULLA',
        'cdate':'DATA CHIUSURA',
        'city':'CITTA\'',
        'contact':'CONTATTO',
        'contacts':'CONTATTI',
        'countryCode':'CODICE NAZIONE',
        'country':'NAZIONE',
        'customer':'CLIENTE',
        'customers':'CLIENTI',
        'description':'DESCRIZIONE',
        'dateFormat':'dd/MM/yyyy',
        'dateFormatSelect':'%d/%m/%Y',
        'days':'GIORNATE',
        'dailyRate':'PREZZO GG',
        'employeesNumber':'NUMERO DI IMPIEGATI',
        'fcst1':'FORECAST 1^ ANNO',
        'fcst2':'FORECAST 2^ ANNO',
        'fcst3':'FORECAST 3^ ANNO',
        'finalCustomer':'CLIENTE FINALE',
        'genericMail':'MAIL GENERICA',
        'headquarter':'SEDE LEGALE',
        'industry':'SETTORE INDUSTRIALE',
        'itemCode':'CODICE EL.',
        'items':'ITEMS',
        'market':'MERCATO',
        'mobile':'CELLULARE',
        'name':'NOME',
        'newContact':'NUOVO CONTATTO',
        'newCustomer':'NUOVO CLIENTE',
        'newEstimate':'NUOVA OFFERTA',
        'newOpportunity':'NUOVA OPPORTUNITA\'',
        'notes':'NOTE',
        'opportunity':'OPPORTUNITA\'',
        'pec':'PEC',
        'pm':'PM',
        'premise':'SEDE   ',
        'premises':'SEDI   ',
        'price':'PREZZO',
        'province':'PROVINCIA',
        'ps':'SERVIZI PROFESSIONALI',
        'qta':'QUANTITA\'',
        'removeItem':'Rimuovi',
        'role':'RUOLO',
        'save':'SALVA',
        'sdi':'SDI',
        'searchCustomers':'CERCA TRA I CLIENTI',
        'searchOpportunities':'CERCA TRA LE OPPORTUNITA\'',
        'street':'STVIAREET',
        'surname':'COGNOME',
        'tecbd':'RICHIESTO SUPP.TECNICO',
        'telephone':'TELEFONO',
        'territory':'ZONA',
        'toEstimate':'Crea Offerta',
        'totalAmount':'Costo complessivo',
        'totalPrice':'Prezzo totale    ',
        'totalVAT':'IVA totale       ',
        'ttAddContact':'Aggiungi nuovo contatto',
        'ttAddCustomer':'Aggiungi nuovo Cliente',
        'ttAddItems':'Aggiungi un elemento',
        'ttAddOpportunity':'Aggiungi una nuova Opportunità',
        'ttAddPremise':'Aggiungi nuova sede',
        'ttAddPSs':'Aggiungi Servizi Professionali',
        'ttHideItems':'Nascondi',
        'ttHidePSs':'Nascondi Servizi Professionali',
        'turnover':'FATTURATO',
        'update':'MODIFICA',
        'uprice':'PREZZO UNIT.',
        'vat':'P.IVA',
        'website':'SITO WEB',
        'winpro':'PROB.SUCC.',
        'zip':'CAP',
    },
    'en': {
        'amount':'AMOUNT',
        'assignedto':'ASSIGNED TO',
        'bu':'BUSINESS UNIT',
        'cancel':'CANCEL',
        'cdate':'CLOSE DATE  ',
        'city':'CITY',
        'contact':'CONTACT',
        'contacts':'CONTACTS',
        'countryCode':'COUNTRY CODE',
        'country':'COUNTRY',
        'customer':'CUSTOMER',
        'customers':'CUSTOMERS',
        'dateFormat':'MM/dd/yyyy',
        'dateFormatSelect':'%m/%d/%Y',
        'days':'DAYS',
        'dailyRate':'DAILY RATE',
        'description':'DESCRIPTION',
        'employeesNumber':'EMPLOYEES NUMBER',
        'fcst1':'FORECAST 1^ YEAR',
        'fcst2':'FORECAST 2^ YEAR',
        'fcst3':'FORECAST 3^ YEAR',
        'finalCustomer':'END CUSTOMER',
        'genericMail':'GENERIC MAIL',
        'headquarter':'HEADQUARTER',
        'industry':'INDUSTRY',
        'itemCode':'ITEM CODE',
        'items':'ITEMS',
        'market':'MARKET',
        'mobile':'MOBILE',
        'name':'NAME',
        'newContact':'NEW CONTACT',
        'newCustomer':'NEW CUSTOMER',
        'newEstimate':'NEW ESTIMATE',
        'newOpportunity':'NEW OPPORTUNITY',
        'notes':'NOTES',
        'opportunity':'OPPORTUNITY',
        'pec':'PEC',
        'pm':'PM',
        'premise':'PREMISE',
        'premises':'PREMISES',
        'price':'PRICE ',
        'province':'STATE',
        'ps':'PROFESSIONAL SERVICES',
        'qta':'QUANTITY ',
        'removeItem':'Remove ',
        'role':'ROLE ',
        'save':'SAVE',
        'sdi':'SDI',
        'searchCustomers':'SEARCH CUSTOMERS',
        'searchOpportunities':'SEARCH OPPORTUNITIES',
        'street':'STREET',
        'surname':'SURNAME',
        'tecbd':'TECH.SUPPORT REQUIRED ',
        'telephone':'TELEPHONE',
        'territory':'TERRITORY',
        'toEstimate':'Create Estimate',
        'totalAmount':'Total amount',
        'totalPrice': 'Total price ',
        'totalVAT':   'Total VAT   ',
        'ttAddContact':'Add new contact',
        'ttAddCustomer':'Add new Customer',
        'ttAddItems':'Add an item',
        'ttAddOpportunity':'Add a new Opportunity',
        'ttAddPremise':'Add new premise',
        'ttAddPSs':'Add Professional Services',
        'ttHideItems':'Hide items',
        'ttHidePSs':'Hide Professional Services',
        'turnover':'TURNOVER',
        'update':'UPDATE',
        'uprice':'UNIT PRICE ',
        'vat':'VAT',
        'website':'WEB SITE',
        'winpro':'WIN PROB. ',
        'zip':'ZIP',
    }
};

export {Titles, MenusItems};